# Generated by Django 5.0.7 on 2025-04-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('job_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('wishlist', 'Wishlist'), ('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('interview_platform', models.CharField(blank=True, max_length=100)),
                ('interview_notes', models.TextField(blank=True)),
            ],
        ),
    ]
