# Generated by Django 5.0.7 on 2025-04-14 13:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='role',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='date_applied',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='interview_date',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='interview_notes',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='interview_platform',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job_url',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='applied_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Screening', 'Screening'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('type', models.CharField(choices=[('Technical', 'Technical'), ('HR', 'HR'), ('Managerial', 'Managerial'), ('Other', 'Other')], max_length=20)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.jobapplication')),
            ],
        ),
    ]
