# Generated by Django 5.0.7 on 2025-04-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_rename_company_name_jobapplication_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
