# Generated by Django 5.0.7 on 2026-02-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_jobapplication_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Ghosted', 'Ghosted'), ('Interviewing', 'Interviewing'), ('Assessment', 'Assessment')], default='Applied', max_length=20),
        ),
    ]
