# Generated by Django 5.0.7 on 2026-02-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_add_application_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='type',
            field=models.CharField(choices=[('Technical', 'Technical'), ('HR', 'HR'), ('Behavioral', 'Behavioral'), ('Final', 'Final'), ('Phone Screen', 'Phone Screen'), ('System Design', 'System Design')], max_length=20),
        ),
    ]
