# Generated by Django 5.0.7 on 2026-02-03 16:18

import datetime
from django.conf import settings
from django.db import migrations, models


def check_no_duplicate_job_applications(apps, schema_editor):
    """Check for duplicate job applications before adding unique constraint"""
    JobApplication = apps.get_model('applications', 'JobApplication')
    
    # Find duplicates grouped by (user_id, company, position) with status in ['Applied', 'Interviewing', 'Assessment']
    duplicates = (
        JobApplication.objects
        .filter(status__in=['Applied', 'Interviewing', 'Assessment'])
        .values('user_id', 'company', 'position')
        .annotate(count=models.Count('id'))
        .filter(count__gt=1)
    )
    
    if duplicates.exists():
        duplicate_list = list(duplicates)
        error_messages = [
            f"User {d['user_id']}, Company '{d['company']}', Position '{d['position']}' ({d['count']} duplicates)"
            for d in duplicate_list
        ]
        raise RuntimeError(
            f"Found duplicate job applications that violate the unique constraint:\n" +
            "\n".join(error_messages) +
            "\n\nPlease remove or consolidate duplicates before running this migration."
        )


def reverse_check(apps, schema_editor):
    """Reverse operation - nothing to do"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_make_user_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-applied_date']},
        ),
        migrations.RenameIndex(
            model_name='interview',
            new_name='application_date_b79f54_idx',
            old_name='applications_interview_date_time_idx',
        ),
        migrations.RenameIndex(
            model_name='interview',
            new_name='application_job_app_a64cb6_idx',
            old_name='applications_interview_app_date_idx',
        ),
        migrations.RenameIndex(
            model_name='jobapplication',
            new_name='application_user_id_42b6ac_idx',
            old_name='applications_user_applied_idx',
        ),
        migrations.RenameIndex(
            model_name='jobapplication',
            new_name='application_user_id_16fc9d_idx',
            old_name='applications_user_status_idx',
        ),
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applied_date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.RunPython(check_no_duplicate_job_applications, reverse_check),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['Applied', 'Interviewing', 'Assessment'])), fields=('user', 'company', 'position'), name='unique_user_application'),
        ),
    ]
