# Generated by Django 5.0.7 on 2026-02-03 16:18

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_make_user_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-applied_date']},
        ),
        migrations.RenameIndex(
            model_name='interview',
            new_name='application_date_b79f54_idx',
            old_name='applications_interview_date_time_idx',
        ),
        migrations.RenameIndex(
            model_name='interview',
            new_name='application_job_app_a64cb6_idx',
            old_name='applications_interview_app_date_idx',
        ),
        migrations.RenameIndex(
            model_name='jobapplication',
            new_name='application_user_id_42b6ac_idx',
            old_name='applications_user_applied_idx',
        ),
        migrations.RenameIndex(
            model_name='jobapplication',
            new_name='application_user_id_16fc9d_idx',
            old_name='applications_user_status_idx',
        ),
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applied_date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['Applied', 'Interviewing', 'Assessment'])), fields=('user', 'company', 'position'), name='unique_user_application'),
        ),
    ]
