# Generated by Django 5.0.7 on 2026-02-03 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_alter_interview_options_alter_jobapplication_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobapplication',
            name='unique_user_application',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Ghosted', 'Ghosted'), ('Interviewing', 'Interviewing'), ('Assessment', 'Assessment'), ('Offered', 'Offered')], default='Applied', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['Applied', 'Interviewing', 'Assessment', 'Offered'])), fields=('user', 'company', 'position'), name='unique_user_application'),
        ),
    ]
